### ISSUE TITLE
Caprine needs updating and add to CompileCommands.md

### ISSUE THREAD

**Issue by Botspot** [Pi-Apps-Coders/files#33]
I experienced a dark-mode bug in Caprine today, and when I [asked](https://github.com/sindresorhus/caprine/issues/1809#issuecomment-1159012286) the devs about it, they said this was fixed in Caprine version 2.55.5,

I would have updated the debs myself, but I don't see any instructions for how to do it in CompileCommands.md. And while it may be simple to track down the instructions, I have a Windows 10 VM and flatpak compatibility layer to work on. 👀

Pinging the uploader of these debs, @cycool29.

**Comment by cycool29** [comment]
Sorry for the late reply, here are the commands to build the debs:

```bash
git clone https://github.com/sindresorhus/caprine
cd caprine
npm install
npm run build
electron-builder -l deb --arm64 # for arm64
electron-builder -l deb --armv7l # for armv7l
```

I will open a PR to add these commands to CompileCommands.md.
