### ISSUE TITLE
Update Deskreen

### ISSUE THREAD

**Issue by Botspot** [Pi-Apps-Coders/files#35]
Somebody on the Pi-Apps Deskreen PR requested if it could be updated to a later version.
https://github.com/Botspot/pi-apps/pull/1094#issuecomment-1186465300

Pinging @ryanfortner and @Crilum because they were mentioned in the app's `credits` file.
I may have taken care of this myself if the build commands were available in CompileCommands.md, but they were not.

Thank you for asking about this, @EDIflyer!

**Comment by Crilum** [comment]
I wasn't able to build Deskreen a couple months ago.. And I don't remember what I did to get it to work, when I did build it. Sorry..

I also don't have a Pi anymore, so I can't try again. (Well, I guess I could try emulating one..)

**Comment by Crilum** [comment]
Actually, I just looked at [an issue I created about ARM builds in the Deskreen repo](https://github.com/pavlobu/deskreen/issues/168), and realized I actually didn't build deskreen... @ryanfortner did.

**Comment by ryanfortner** [comment]
> Actually, I just looked at [an issue I created about ARM builds in the Deskreen repo](https://github.com/pavlobu/deskreen/issues/168), and realized I actually didn't build Deskreen... @ryanfortner did.
> 
> 

See this issue for compile instructions. https://github.com/raspbian-addons/raspbian-addons/issues/48

**Comment by EDIflyer** [comment]
> > Actually, I just looked at [an issue I created about ARM builds in the Deskreen repo](https://github.com/pavlobu/deskreen/issues/168), and realized I actually didn't build Deskreen... @ryanfortner did.
> 
> See this issue for compile instructions. [raspbian-addons/raspbian-addons#48](https://github.com/raspbian-addons/raspbian-addons/issues/48)

That would be great if it could be added 👍

**Comment by theofficialgman** [comment]
so someone requesting ARM builds of lzma-native here would be helpful: https://github.com/addaleax/lzma-native

**Comment by theofficialgman** [comment]
edit: `I'm using arm32 (with aarch64 kernel..). Does that make a difference?`

actually more specifically, they need to build for armhf. lzma-naitve is available for arm64 linux

**Comment by theofficialgman** [comment]
> I just installed lzma-native on my armhf OS. Maybe I'm missing something, but `$ npm install --save lzma-native` seems to have succeeded.

the install works.... it won't actually run because it doesn't have an armhf binary

**Comment by theofficialgman** [comment]
just built an ARM64 build:
```
cd
git clone https://github.com/pavlobu/deskreen.git
cd deskreen
git checkout v2.0.3
# edit package.json at this point "package" to include --arm64
cd ~/deskreen/app/client
NODE_OPTIONS=--openssl-legacy-provider yarn install --frozen-lockfile
cd ~/deskreen
NODE_OPTIONS=--openssl-legacy-provider yarn install --frozen-lockfile
cd ~/deskreen/app
NODE_OPTIONS=--openssl-legacy-provider yarn install --frozen-lockfile
cd ~/deskreen
NODE_OPTIONS=--openssl-legacy-provider yarn package
```
yes this is what the official build instructions do (with the added openssl-legacy-provider so I can run on npm 17+)

**Comment by theofficialgman** [comment]
and here is the appimage https://github.com/Pi-Apps-Coders/files/releases/download/large-files/Deskreen-2.0.3-arm64.AppImage

**Comment by theofficialgman** [comment]
and the deb https://github.com/Pi-Apps-Coders/files/releases/download/large-files/deskreen_2.0.3_arm64.deb

**Comment by theofficialgman** [comment]
hmm.. actually I was able to build an armhf build without issue regarding lzma-native, it just compiled during the build

@Botspot I will upload that in a bit when it finishes packaging the deb. then we can close this issue

**Comment by theofficialgman** [comment]
@Botspot the deb is posted, can you please test it and update pi-apps. I am leaving to go out of town for a couple of days rn.
assuming the armhf deb works, you can transition the pi-apps install-32 to use the deb as well like the install-64 which already uses the deb

**Comment by Botspot** [comment]
> @Botspot the deb is posted, can you please test it and update pi-apps. I am leaving to go out of town for a couple of days rn. assuming the armhf deb works, you can transition the pi-apps install-32 to use the deb as well like the install-64 which already uses the deb

It worked fine on my system, so I've updated the scripts.
@theofficialgman, when you have some spare time, could you post your full compilation and deb-creation steps in the CompileCommands.md?

**Comment by theofficialgman** [comment]
@Botspot done. https://github.com/Pi-Apps-Coders/files/commit/ef8ea6e0c5b9736300cab6614c2953d6c6d224fd
